language: android
jdk: oraclejdk8
env:
 global:
 - ANDROID_SDK=25
 - ANDROID_BUILD_TOOLS=25.0.2
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_SDK

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-26
    # - sys-img-armeabi-v7a-android-17
install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.1"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.1"
before_script: cd GCBACallejero
script:
- ./gradlew :callejerogcba:assembleRelease
- ./gradlew :app:assembleDebug